jobboardscraper/jobboardscraper/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse_lazy

from .views import FaviconView, HomeView, RobotsView

urlpatterns = [

    # Admin password reset
    url(r'^admin/password_reset/$', auth_views.password_reset, name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # Admin
    url(r'^admin/logout/$', auth_views.logout, {'next_page': reverse_lazy('admin:index')}),
    url(r'^admin/', admin.site.urls),

    # Public
    url(r'^jobs/', include('jobs.urls')),
    url(r'^organizations/', include('organizations.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^favicon\.ico$', FaviconView.as_view(), name='favicon'),
    url(r'^robots\.txt$', RobotsView.as_view(), name='robots'),
    url(r'^$', HomeView.as_view(), name='home'),

]


# Static/media for local development
if getattr(settings, 'DEBUG', False):
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobboardscraper/jobs/urls.py
from django.conf.urls import url

from .views import JobDetailView, JobListView


urlpatterns = [

    url(r'^(?P<pk>[\d]+)/$', JobDetailView.as_view(), name='job_detail'),

    url(r'^$', JobListView.as_view(), name='job_list'),

]

jobboardscraper/organizations/urls.py
from django.conf.urls import url

from .views import OrganizationDetailView, OrganizationListView


urlpatterns = [

    url(r'^(?P<slug>[-\w]+)/$', OrganizationDetailView.as_view(), name='organization_detail'),

    url(r'^$', OrganizationListView.as_view(), name='organization_list'),

]

jobboardscraper/search/urls.py
from django.conf.urls import url

from .views import MySearchView


urlpatterns = [

    url(r'^$', MySearchView.as_view(), name='search'),

]

jobboardscraper/jobs/models.py
from django.core.urlresolvers import reverse
from django.db import models

from organizations.models import Organization


class Board(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    url = models.URLField("URL")

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return "%s" % self.title


class Job(models.Model):
    board = models.ForeignKey(Board)
    title = models.CharField(max_length=255)
    organization = models.ForeignKey(Organization, blank=True, null=True)
    body = models.TextField()
    url = models.URLField("URL")
    pub_date = models.DateTimeField()
    scrape_date = models.DateTimeField()

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        return reverse("job_detail", args=[str(self.pk)])

jobboardscraper/organizations/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Organization(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    email = models.EmailField(blank=True)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        return reverse("organization_detail", args=[str(self.slug)])

jobboardscraper/search/forms.py
from django import forms

from haystack.forms import SearchForm


class MySearchForm(SearchForm):
    q = forms.CharField(required=False, label='Query', widget=forms.TextInput(attrs={
        'type': 'search',
        'autocorrect': 'off',
        'class': 'form-control',
        'placeholder': 'Search jobs',
    }))

    def search(self):
        sqs = super(MySearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()
        sqs = sqs.order_by('-pub_date')
        return sqs

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(MySearchForm, self).__init__(*args, **kwargs)
        if self.request:
            if 'q' in self.request.GET:
                copy = self.request.GET.copy()
                self.fields['q'].initial = copy['q'].strip()

jobboardscraper/jobboardscraper/views.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import RedirectView, TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'


class FaviconView(RedirectView):
    url = staticfiles_storage.url('img/favicon.ico')
    permanent = True


class RobotsView(TemplateView):
    template_name = 'robots.txt'
    content_type = 'text/plain'

jobboardscraper/jobs/views.py
from django.conf import settings
from django.views.generic import DetailView, ListView

from pure_pagination.mixins import PaginationMixin

from .models import Job


class JobDetailView(DetailView):
    model = Job


class JobListView(PaginationMixin, ListView):
    model = Job
    paginate_by = getattr(settings, 'PAGINATE_BY', 10)

jobboardscraper/organizations/views.py
from django.views.generic import DetailView, ListView

from pure_pagination.mixins import PaginationMixin

from .models import Organization


class OrganizationDetailView(DetailView):
    model = Organization


class OrganizationListView(PaginationMixin, ListView):
    model = Organization
    paginate_by = 50

jobboardscraper/search/views.py
from django.conf import settings

from haystack.generic_views import SearchView
from pure_pagination.mixins import PaginationMixin

from .forms import MySearchForm


class MySearchView(PaginationMixin, SearchView):
    form_class = MySearchForm
    paginate_by = getattr(settings, 'PAGINATE_BY', 10)

jobboardscraper/templates/base.html
<!DOCTYPE html>

{% load i18n staticfiles %}

<html lang="{% get_current_language as language %}{{ language }}">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{{ request.site.name }}{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <header class="site-header">
                        <a href="{% url 'home' %}" class="navbar-brand">{{ request.site.name }}</a>
                    </header>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="{% block jobs_active %}{% endblock %}"><a href="{% url 'job_list' %}">Jobs</a></li>
                        <li class="{% block organizations_active %}{% endblock %}"><a href="{% url 'organization_list' %}">Organizations</a></li>
                        <li class="{% block search_active %}{% endblock %}"><a href="{% url 'search' %}">Search</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            {% block search %}

                            {{ search_form.non_field_errors }}

                            <form method="get" action="{% url 'search' %}" class="navbar-form navbar-right">

                                {% for field in search_form %}
                                    {% if field.is_hidden %}
                                    {{ field }}
                                    {% endif %}
                                {% endfor %}

                                <div class="input-group">
                                    {{ search_form.q }}
                                    <span class="input-group-btn">
                                        <button type="submit" data-submit="Searching" class="btn btn-default">Search</button>
                                    </span>
                                </div>

                            </form>
                            {% endblock %}
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</nav>

<main class="site-main">
    {% block content_container %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    {% endblock %}
</main>

<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                {% block footer %}
                <p>&copy; {% now "Y" %}. <a href="{% url 'home' %}">{{ request.site.name }}</a>.</p>
                {% endblock %}
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

jobboardscraper/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}


{% block content_container %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>{{ request.site.name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">

            <p><strong>Job Board Scraper</strong> collects, cleans, organizes, and indexes English teaching positions from an <a href="http://www.eslcafe.com/jobs/korea/">existing online job board</a> once a day.</p>

            <p>The code scrapes the job board with <a href="http://scrapy.org/">Scrapy</a> and integrates it into a <a href="https://www.djangoproject.com/">Django</a> website with an <a href="https://www.elastic.co/">Elasticsearch</a> search index and a <a href="https://www.postgresql.org/">PostgreSQL</a> database. The website is hosted on <a href="https://www.heroku.com/">Heroku</a>.</p>

            <ul>
                <li><a href="https://github.com/richardcornish/jobboardscraper">Code repository</a></li>
                <li><a href="https://jobboardscraper.herokuapp.com/">Deployed app</a></li>
            </ul>

            <h2>How it works</h2>

            <p>The <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/scraper/spiders/eslcafe.py">spider</a> is scheduled once a day to visit the <a href="http://www.eslcafe.com/jobs/korea/">job board website</a> and to <a href="http://doc.scrapy.org/en/1.1/topics/spiders.html">follow each job</a> via <a href="http://doc.scrapy.org/en/1.1/topics/selectors.html">XPath selection</a>.</p>

            <p>The <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/scraper/items.py">data is mapped</a> to a <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/jobs/models.py">Django model</a> with the <a href="https://github.com/scrapy-plugins/scrapy-djangoitem"><code>scrapy-djangoitem</code></a> extension. Any additional fields are manually attached to the <a href="http://doc.scrapy.org/en/1.1/topics/items.html">item</a>.</p>

            <p>The data is <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/scraper/pipelines.py">cleaned, converted, and saved</a> in a <a href="http://doc.scrapy.org/en/1.1/topics/item-pipeline.html">pipeline</a>. The code checks and prevents job duplicates from being saved. Additionally, it separates the job from the organization and stores the data in different models, normalizing the original data, which allows the ability to browse <a href="{% url 'job_list' %}">jobs</a> and <a href="{% url 'organization_list' %}">organizations</a> separately, a feature not on the original website.</p>

            <p>Search is handled by <a href="http://haystacksearch.org/">Haystack</a> and <a href="https://elements.heroku.com/addons/searchbox">SearchBox</a>. To use Haystack, the code includes a <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/search/forms.py">search form</a>, a <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/search/views.py">search view</a>, a <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/templates/search/search.html">search template</a>, a <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/jobs/search_indexes.py">search index</a>, and an <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/templates/search/indexes/jobs/job_text.txt">index template</a>, all of which is <a href="http://django-haystack.readthedocs.io/en/latest/tutorial.html">outlined in the documentation</a>.</p>

            <p>Future scraping and indexing are handled by a <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/jobboardscraper/celery.py">Celery app</a> and its <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/jobs/tasks.py">tasks</a> with a <a href="https://github.com/richardcornish/jobboardscraper/blob/master/jobboardscraper/jobboardscraper/settings.py#L214">Redis broker</a>, which are both outlined in the <a href="http://celery.readthedocs.io/en/latest/django/first-steps-with-django.html">Celery</a> and <a href="https://devcenter.heroku.com/articles/celery-heroku">Heroku</a> documentation. The <a href="http://celery.readthedocs.io/en/latest/userguide/periodic-tasks.html#starting-the-scheduler">Celery beat service</a> is embedded in the Celery worker to stay within usage of one dyno.</p>

            <p>Installation and deployment instructions are in the <a href="https://github.com/richardcornish/jobboardscraper/blob/master/README.md"><code>README</code></a> of the code repository.</p>

            <h2>Resources</h2>

            <p>Some resources that helped me figure things out:</p>

            <ul>
                <li><a href="https://github.com/sammyfung/hk0weather">hk0weather</a>, a Hong Kong weather data project by <a href="http://sammy.hk/">Sammy Fung</a></li>
                <li><a href="http://www.slideshare.net/sammyfung/python-web-scraping-and-content-management-scrapy-and-django">Python, Web scraping and content management: Scrapy and Django</a></li>
                <li><a href="http://www.slideshare.net/sammyfung/hk0weather-barcamp">Open Data, Open Government</a></li>
                <li><a href="http://newcoder.io/scrape/">Web scraper</a> tutorial by <a href="http://www.roguelynn.com/">Lynn Root</a></li>
                <li><a href="https://devcenter.heroku.com/articles/django-app-configuration">Configuring Django Apps for Heroku</a> by Heroku</li>
            </ul>

        </div>
        <div class="col-sm-6 col-md-4 col-md-offset-1">
            <a href="http://www.eslcafe.com/jobs/korea/"><img src="{% static 'img/screenshot.png' %}" alt="Screenshot" class="img-responsive img-thumbnail"></a>
        </div>
    </div>
</div>
{% endblock %}

jobboardscraper/templates/includes/_pagination.html
{% if is_paginated %}
<div class="text-center">
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li><a href="?{{ page_obj.previous_page_number.querystring }}">&laquo;</a></li>
            {% endif %}
            {% for page in page_obj.pages %}
                {% if page %}
                    {% ifequal page page_obj.number %}
                        <li class="active"><span>{{ page }}</span></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li><span>...</span></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li><a href="?{{ page_obj.next_page_number.querystring }}">&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

jobboardscraper/templates/includes/pagination.html
{% if is_paginated %}
<div class="text-center">
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% endif %}
            {% for number in paginator.page_range %}
            <li{% ifequal page_obj.number number %} class="active"{% endifequal %}><a href="?page={{ number }}">{{ number }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

jobboardscraper/templates/jobs/job_detail.html
{% extends "base.html" %}

{% load tz %}


{% block title %}{{ job.title }} &#183; {{ block.super }}{% endblock %}


{% block jobs_active %}active{% endblock %}


{% block content %}

<h1>{{ job.title }}</h1>

<p>{{ job.pub_date|localtime }}</p>

<div class="body">
    {{ job.body|safe }}
</div>

{% if job.organization %}
<h2>Organization</h2>
<p><a href="{{ job.organization.get_absolute_url }}">{{ job.organization.title }}</a></p>
{% if job.organization.email %}
<p><a href="mailto:{{ job.organization.email }}">{{ job.organization.email }}</a></p>
{% endif %}
{% endif %}

<h2>Source</h2>
<p><a href="{{ job.url }}" rel="external">{{ job.board.title }}</a></p>

{% endblock %}

jobboardscraper/templates/jobs/job_list.html
{% extends "base.html" %}

{% load tz humanize %}


{% block title %}Jobs &#183; {{ block.super }}{% endblock %}


{% block jobs_active %}active{% endblock %}


{% block content %}

<h1>Jobs</h1>

<p>{{ paginator.count|intcomma }} job{{ paginator.count|pluralize }}</p>

<ul>
    {% for job in job_list %}
    <li>
        <a href="{{ job.get_absolute_url }}">{{ job.title }}</a><br>
        <a href="{{ job.organization.get_absolute_url }}">{{ job.organization }}</a><br>
        {{ job.pub_date|localtime }}
    </li>
    {% endfor %}    
</ul>

{% include 'includes/_pagination.html' %}

{% endblock %}

jobboardscraper/templates/organizations/organization_detail.html
{% extends "base.html" %}

{% load tz %}


{% block title %}{{ organization.title }} &#183; {{ block.super }}{% endblock %}


{% block organizations_active %}active{% endblock %}


{% block content %}

<h1>{{ organization.title }}</h1>

{% if organization.email %}
<h2>Contact</h2>
<p><a href="mailto:{{ organization.email }}">{{ organization.email }}</a></p>
{% endif %}

<h2>Jobs</h2>

<ul>
    {% for job in organization.job_set.all %}
    <li>
        <a href="{{ job.get_absolute_url }}">{{ job.title }}</a><br>
        {{ job.pub_date|localtime }}
    </li>
    {% empty %}
    <li>No jobs available.</li>
    {% endfor %}
</ul>

{% endblock %}

jobboardscraper/templates/organizations/organization_list.html
{% extends "base.html" %}

{% load humanize %}


{% block title %}Organizations &#183; {{ block.super }}{% endblock %}


{% block organizations_active %}active{% endblock %}


{% block content %}

<h1>Organizations</h1>

<p>{{ paginator.count|intcomma }} organization{{ paginator.count|pluralize }}</p>

<ul>
    {% for organization in organization_list %}
    <li><a href="{{ organization.get_absolute_url }}">{{ organization.title }}</a> {{ organization.job_set.all|length }}</li>
    {% endfor %}    
</ul>

{% include 'includes/_pagination.html' %}

{% endblock %}

jobboardscraper/templates/search/search.html
{% extends 'base.html' %}

{% load widget_tweaks highlight humanize %}


{% block title %}Search {% if query %}&#8220;{{ query }}&#8221;{% endif %} &#183; {{ block.super }}{% endblock %}


{% block search_active %}active{% endblock %}


{% block search %}
{% endblock %}


{% block content %}

<h1>Search</h1>

<div class="row">
    <div class="col-lg-12">

        {{ search_form.non_field_errors }}

        <form method="get" action="{% url 'search' %}">

            {% for field in search_form %}
                {% if field.is_hidden %}
                {{ field }}
                {% endif %}
            {% endfor %}

            <div class="input-group">
                {{ search_form.q|attr:"autofocus:autofocus"|add_class:"input-lg" }}
                <span class="input-group-btn">
                    <button type="submit" data-submit="Searching" class="btn btn-lg btn-primary">Search</button>
                </span>
            </div>

        </form>

    </div>
</div>

{% if query %}

    {% if object_list %}
        <h2>Results {{ page_obj.start_index }}&#8211;{{ page_obj.end_index }} of {{ page_obj.paginator.count|intcomma }}</h2>
    {% else %}
        <h2></h2>
        <p>No results found.</p>
    {% endif %}

    {% if object_list %}
        {% for result in object_list %}
        <div class="result">
            <p><a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a></p>
            <p>{% highlight result.object.body with query %}</p>
        </div>
        {% endfor %}
    {% endif %}

    {% include 'includes/_pagination.html' %}

{% endif %}

{% endblock %}